Hcaptcha integration smart contracts
metamask-human/metamask-extension pull request #8
Opened 2020-12-11 09:06 UTC by IvanTrutnev

2020-12-11 09:31 UTC, vkomodey requested changes

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/send-content.component.js
> +            <SendCaptchaRow updateGas={this.updateGas} isSmartContract={isSmartContract} />
in case isSmartContract is true, this component will not be rendered, so your props passing is useless here(as well as all code in the SendCaptchaRow connected to smart contracts logic)

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +    const hexData = isSmartContract ? data : calculateHexData(data, isHcaptchaVerified)
one thing that is not related particulary to this PR, but still. What do you think of renaming the `calculateHexData` to `appendProofOfHumanityToData`?

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +    const hexData = isSmartContract ? data : calculateHexData(data, isHcaptchaVerified)
please, do not add vendor names to your variables names

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +    const hexData = isSmartContract ? data : calculateHexData(data, isHcaptchaVerified)
also not related to this PR, but I told you somewhere, that captcha can not be verified. We are verifying the metamask user

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/tests/send-hex-data-row.test.js
> +    it('should not add is_human= postfix to the transaction data if it is smart contract', function() {
let's call is_human postfix - proof of humanity postfix

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/tests/send-content-component.test.js
> +    it('should not render the SendCaptchaRow if that is smart contract', function () {
if *receiver* accounts is contract account

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send.component.js
> +  basicGasEstimated = false
what is `basic gas` actually means and do we need this logic here?

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send.component.js
> +    if (this.basicGasEstimated) {
why do you skip the render in case gas has been estimated?

2020-12-11 09:31 UTC, vkomodey commented on ui/app/pages/send/send-content/send-captcha-row/send-captcha-data-row.component.js
> +    const { isSmartContract } = this.props
isReceiverIsContractAccount

2020-12-14 08:03 UTC, vkomodey requested changes

2020-12-14 08:06 UTC, vkomodey commented on ui/app/pages/send/send-content/send-content.component.js
> +            <SendCaptchaRow updateGas={this.updateGas} isSmartContract={isSmartContract} />
`isSmartContract` prop in the SendCaptchaRow always equals to `false`. There is no `if` branch where this prop will be positive. So because of that, this prop is extra in the SendCaptchaRow component

2020-12-14 09:49 UTC, vkomodey requested changes

2020-12-14 09:49 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +      isReceiverContractAccount
Why do you need who is receiver in the captcha related component? I thought, that it is handled by the parent component(do not render the captcha in case receiver is a Contract Account)

2020-12-14 09:49 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +      isReceiverContractAccount
I think we can easilly delete this prop from the component

2020-12-14 10:01 UTC, IvanTrutnev commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +      isReceiverContractAccount
We need isReceiverContractAccount to check must added is_human postfix when user is writing some data in textarea or not

2020-12-14 10:05 UTC, vkomodey commented on ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
> +      isReceiverContractAccount
ahh, sorry. that is the data component. my fault

2020-12-14 10:08 UTC, merged